FROM ghcr.io/homebrew/brew:latest
RUN brew install fish starship fzf ripgrep \
  git \
  helix \
  gh \
  lazygit \
  pyright ruff black \
  rust-analyzer \
  ansible-language-server \
  terraform-ls \
  bash-language-server \
  vscode-langservers-extracted \
  typescript-language-server \
  dockerfile-language-server
