name: Build and Push Docker Image - brew-toolbox

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: Homebrew/brew
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch origin/master from Git
        run: git fetch origin master

      - name: Login to Github Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Push the Docker image
        env:
          IMAGE: brew-toolbox
        run: |
          # See Ubuntu Image: https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md
          # See Homebrew Dockerfile https://github.com/Homebrew/brew/blob/master/Dockerfile
          sed -i 's_FROM ubuntu_FROM quay.io/toolbx/ubuntu-toolbox_' Dockerfile

          docker build . --file Dockerfile --tag ${IMAGE}

          docker tag ${IMAGE} "ghcr.io/kulabun/${IMAGE}:latest"
          docker push "ghcr.io/kulabun/${IMAGE}:latest"
          
          docker tag ${IMAGE} "ghcr.io/kulabun/${IMAGE}:$(date +%s)"
          docker push "ghcr.io/kulabun/${IMAGE}:$(date +%s)"
