name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          cd ./devbox
          docker build . --file Dockerfile --tag devbox
    
      - name: Push the Docker image
        run: |
          docker tag devbox "ghcr.io/kulabun/devbox:latest"
          docker push "ghcr.io/kulabun/devbox:latest"
          
          docker tag devbox "ghcr.io/kulabun/devbox:$(date +%s)"
          docker push "ghcr.io/kulabun/devbox:$(date +%s)"
