name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 * * 0' # every sunday
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
