name: Build and Push Docker Image - open-webui

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    paths:
      - .github/workflows/open-webui.yml
      - open-webui/Dockerfile
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push the Docker image
        env:
          IMAGE: open-webui
        run: |
          cd ./${IMAGE}
          docker build . --file Dockerfile --tag ${IMAGE}

          docker tag ${IMAGE} "kulabun/${IMAGE}:latest"
          docker push "kulabun/${IMAGE}:latest"

          docker tag ${IMAGE} "kulabun/${IMAGE}:$(date +%s)"
          docker push "kulabun/${IMAGE}:$(date +%s)"
